---
title:               Jeremy Haberman
tagline:             Tagline
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Jeremy Haberman
twitter:             jeremyhaberman
github:              jeremyhaberman
email:               jeremy@jeremyhaberman.com
google_analytics_id: YOUR_GA_ID
disqus_shortname:    <%= ENV.fetch("disqus_shortname") { "" } %>
